# Documentation at https://circleci.com/docs/2.0/language-python/
version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
          - v3-dependencies-{{ checksum "setup.py" }}

      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            venv/bin/pip install --upgrade pip setuptools pytest
            venv/bin/pip install --upgrade .

      - save_cache:
          paths:
            - venv
          key: v3-dependencies-{{ checksum "setup.py" }}

      - run:
          name: run tests
          command: |
            source venv/bin/activate
            ./test.sh
